services:
  postgres:
    image: postgres:16

    container_name: game_db

    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: game_db

    ports:
      - "5436:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d game_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .

    container_name: game_api

    restart: unless-stopped

    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:password@postgres:5432/game_db

    ports:
      - "8000:8000"

    depends_on:
      postgres:
        condition: service_healthy

    volumes:
      - .:/code

volumes:
  postgres_data: